apiVersion: v1
kind: Secret
metadata:
  name: policy-claims-secrets
  namespace: policy-claims
type: Opaque
stringData:
  JWT_SECRET: change-me-k8s
  MONGODB_URI: mongodb://mongo-service:27017/policy_claims_tracker
