services:
  mongo:
    image: mongo:7
    container_name: pct-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./capstone-api
    container_name: pct-api
    environment:
      MONGODB_URI: mongodb://mongo:27017/policy_claims_tracker
      JWT_SECRET: change-me-dev
      PORT: 4000
      CLIENT_ORIGIN: http://localhost:3000
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  client:
    build:
      context: ./capstone-client
    container_name: pct-client
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  mongo_data:
